version: '3.8'

services:
  # Backend service
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - OLLAMA_URL=${OLLAMA_URL:-http://ollama:11434}
    depends_on:
      - postgres
      - ollama
    volumes:
      - ./src:/app/src

  # Frontend service  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:3001}
    depends_on:
      - backend

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pokerguru
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Ollama service (lightweight model)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Use smaller model for free tier
    command: ["sh", "-c", "ollama serve & sleep 10 && ollama pull phi3:mini"]

volumes:
  postgres_data:
  ollama_data:
