# Railway deployment configuration
# https://railway.app

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "3001"

# Database will be automatically provided by Railway
# DATABASE_URL = "${{Postgres.DATABASE_URL}}"

# For Ollama, use smaller model or external API
OLLAMA_MODEL = "phi3:mini"
OLLAMA_URL = "http://localhost:11434"
